# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partida.Partida'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='turno',
            field=models.IntegerField(default=0),
        ),
    ]
