# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-18 04:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenPieza', models.CharField(default='N', max_length=20)),
                ('esOcupada', models.BooleanField(default=False)),
                ('nombreDeCelda', models.IntegerField(default=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('puntaje', models.IntegerField(default=0)),
                ('ranking', models.IntegerField(default=0)),
                ('posicion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroJugadores', models.IntegerField(default=1, unique=True)),
                ('turnoPartida', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('esFinalizado', models.CharField(max_length=1)),
                ('fechaInicio', models.CharField(max_length=50)),
                ('esTurno', models.IntegerField(default=1)),
                ('piezaEnJuego', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numLadoAsociado', models.IntegerField(default=0)),
                ('esDescartada', models.BooleanField(default=False)),
                ('lado1', models.CharField(max_length=50)),
                ('lado2', models.CharField(max_length=50)),
                ('lado3', models.CharField(max_length=50)),
                ('lado4', models.CharField(max_length=50)),
                ('cantRotacion', models.IntegerField(default=0)),
                ('imagenAsociada', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Terreno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNombreTerreno', models.IntegerField(default=0, unique=True)),
                ('esOcupado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Camino',
            fields=[
                ('terreno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='JugarPartida.Terreno')),
                ('esTe', models.BooleanField()),
                ('ladoLibre', models.IntegerField(default=-1)),
                ('esCruce', models.BooleanField()),
                ('ladoInicio', models.IntegerField(default=-1)),
                ('ladoFinal', models.IntegerField(default=-1)),
            ],
            bases=('JugarPartida.terreno',),
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('terreno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='JugarPartida.Terreno')),
                ('numeroEscudos', models.IntegerField(default=-1)),
                ('esTodoCiudad', models.BooleanField()),
                ('ladoInicio', models.IntegerField(default=-1)),
                ('ladoFinal', models.IntegerField(default=-1)),
                ('unicoLadoLibre', models.IntegerField(default=-1)),
                ('unicoLadoCiudad', models.IntegerField(default=-1)),
            ],
            bases=('JugarPartida.terreno',),
        ),
        migrations.CreateModel(
            name='Granja',
            fields=[
                ('terreno_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='JugarPartida.Terreno')),
                ('conClaustro', models.BooleanField()),
                ('claustroOcupado', models.BooleanField()),
                ('ladoInicio', models.IntegerField(default=-1)),
                ('ladoFinal', models.IntegerField(default=-1)),
                ('unicoLadoLibre', models.IntegerField(default=-1)),
                ('unicoLadoGranja', models.IntegerField(default=-1)),
                ('esTodoGranja', models.BooleanField()),
                ('esquinaLibre', models.IntegerField(default=-1)),
            ],
            bases=('JugarPartida.terreno',),
        ),
        migrations.AddField(
            model_name='terreno',
            name='asocPieza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JugarPartida.Pieza'),
        ),
        migrations.AddField(
            model_name='celda',
            name='piezaid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JugarPartida.Pieza'),
        ),
    ]
