# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_jugadores', models.IntegerField(default=2)),
                ('jugando', models.IntegerField(default=1)),
                ('turnos', models.IntegerField(default=1)),
            ],
        ),
    ]
