# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20161015141902 on 2016-12-11 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador1',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='jugador2',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='cantidad_jugadores',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='j2',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='jugando',
        ),
        migrations.AddField(
            model_name='partida',
            name='jugador2',
            field=models.CharField(default=b'Vacio', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='jugador3',
            field=models.CharField(default=b'Vacio', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='jugador4',
            field=models.CharField(default=b'Vacio', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='jugador5',
            field=models.CharField(default=b'Vacio', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='partida',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Jugador1',
        ),
        migrations.DeleteModel(
            name='Jugador2',
        ),
    ]
