# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-17 22:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathimagen', models.CharField(max_length=9, unique=True)),
                ('pos_x', models.IntegerField(default=1)),
                ('pos_y', models.IntegerField(default=1)),
                ('numLadoAsociado', models.IntegerField(default=0)),
                ('esDescartada', models.BooleanField(default=False)),
                ('lado1', models.CharField(max_length=50)),
                ('lado2', models.CharField(max_length=50)),
                ('lado3', models.CharField(max_length=50)),
                ('lado4', models.CharField(max_length=50)),
                ('esOcupada', models.BooleanField(default=False)),
                ('nombreDeCelda', models.IntegerField(default=1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='pieza_en_juego',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='pieza',
            name='partida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='partida.Partida'),
        ),
    ]
