# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partida', '0002_auto_20161217_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pieza',
            name='partida',
        ),
        migrations.RemoveField(
            model_name='partida',
            name='pieza_en_juego',
        ),
        migrations.DeleteModel(
            name='Pieza',
        ),
    ]
